@include('pages/index')
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ asset("style/css/bootstrap.min.css") }}">
    <link rel="stylesheet" href="{{ asset("style.css") }}">
    <script src="{{ asset("style/js/bootstrap.min.js") }}"></script>
    <script src="{{ asset("style.js") }}"></script>
</head>
<body>
    <div class="scrollTop" onclick="scrollToTop();"></div>
    <div>
        <h2 class="m-5 text-center">17 Tokoh Hebat Dunia</h2>
    </div>
    <div>
        <img src="{{ asset("img/bg2.jpeg") }}" class="img-fluid m-5 rounded mx-auto d-block img-responsive" style="width: 60%" alt="...">
        <p style="padding-left: 7%;">Renaldi Nurmazid - 8 Desember 2022</p>
    </div>
    <div>
        <p style="padding-left: 7%;">17 Tokoh Hebat Dunia :</p>
        <ol style="padding-left: 10%;" type="1">
            <li><a href="#1">William Henry Gates III</a></li>
            <li><a href="#2">Steven Paul Jobs</a></li>
            <li><a href="#3">Mark Elliot Zuckerberg</a></li>
            <li><a href="#4">Jeffrey Preston Bezos</a></li>
            <li><a href="#5">Sir Timothy Jhon Berners-Lee</a></li>
            <li><a href="#6">Lawrence Edward Page</a></li>
            <li><a href="#7">Martin Cooper</a></li>
            <li><a href="#8">Kevin David Mitnick</a></li>
            <li><a href="#9">Linus Benedist Torvalds</a></li>
            <li><a href="#10">Elon Reeve Musk</a></li>
            <li><a href="#11">Jack Ma</a></li>
            <li><a href="#12">Walter Elian Disney</a></li>
            <li><a href="#13">Dennis MacAlistair Ritchie</a></li>
            <li><a href="#14">Anders Heljsberg</a></li>
            <li><a href="#15">Samuel Finley Breese Morse</a></li>
            <li><a href="#16">Sergey Mikhailovich Brin</a></li>
            <li><a href="#17">Stephen Gary Wozniak</a></li>
        </ol>
    </div>
    <hr>
    <div>
        <h4 id="1" class="text-center fw-bold">William Henry Gates III</h4>
        <img src="{{ asset("img/billgates.jpg") }}" class="img-fluid m-5 rounded mx-auto d-block img-responsive" style="width: 40%" alt="...">
    </div>
    <div style="margin:2%;padding-left:5%;padding-right:2%">
        <p class="text-justify">
            Bill Gates memiliki nama lengkap yaitu William Henry Gates III, lahir di Seattle, Washington pada tanggal 28 Oktober 1955. Ia memiliki orang tua yang bernama William Henry Gates dan Mari Maxwell dan Bill Gates bisa dikatakan lahir dari keluarga yang berkecukupan.Ayah Bill Gates adalah seorang pengacara yang sudah cukup terkenal karena sudah mempunyai banyak koneksi dengan orang-orang dan perusahaan-perusahaan ternama. Sementara itu, ibu dari Bill Gates merupakan seorang yang bekerja sebagai Dewan Direktur First Interstate Bank, Pacific Northwest Bell, dan anggota tingkat nasional United Way. Kakek Bill Gates yang bernama J.W. Maxwell merupakan seorang presiden bank nasional.
            <p>
                Di dalam keluarganya, Bill Gates memiliki seorang kakak yang bernama Kristianne dan seorang adik yang bernama Libby. Dalam silsilah keluarga Bill Gates, ia merupakan keturunan keempat, tetapi lebih dikenal dengan nama William Henry Gates III atau “Trey” karena ayahnya memiliki nama “II”.Bill Gates yang merupakan anak kedua dari tiga bersaudara ini mempunyai kecerdasan yang cukup tinggi sehingga ia mengalami kesulitan ketika berada di sekolah karena semangat belajar yang lebih tinggi dibandingkan dengan teman-temannya. Kejeniusan yang da di dalam otak Bill Gates membuat dirinya pintar dan pandai dalam bidang akademis.Ketika orang tua Bill Gates mengetahui bahwa anaknya mempunyai kemampuan otak yang jenius maka mereka memasukkan Bill Gates ke sekolah khusus laki-laki yang cukup terkenal di Seattle dan sekolah itu bernama Lakeside School. Sekolah ini terletak di pantai barat Amerika Serikat.
            </p>
            <p>
                Bill Gates yang awalnya menyukai pelajaran komputer ketika masuk sekolah ini, ia mulai pelajaran yang disukai mulai berpindah menjadi pelajaran komputer dan saat itu ia masih berumur 11 tahun.Bill Gates yang sudah jauh cinta dengan dunia komputer membuat orang tuanya menjadi khawatir karena mereka takut kalau Bill Gates tidak bisa berkonsentrasi ketika sedang belajar. Setelah orang tuanya merasa khawatir maka mereka menghentikan kegiatan Bill Gates yang berhubungan dengan komputer selama satu tahun. Hal ini dilakukan supaya Bill Gates berkonsentrasi dalam kegiatan belajar.Karena rasa keingintahuan Bill Gates sangat tinggi yang tidak bisa didapatkan dengan kegiatan belajar maka ia mengalihkan perhatiannya dengan membaca buku-buku seperti bisnis, sastra, sains, dan biografi tokoh terkenal di dunia. Hal yang ingin dicari oleh Bill Gates ketika membaca buku biografi adalah bagaimana caranya untuk menjadi seseorang yang hebat di bidang yang disukainya. Kedua orang tua Bill Gates menyuruh anaknya untuk berhenti mempelajari komputer bukan tanpa alasan. Mereka melakukan itu semua supaya Bill Gates bisa masuk ke universitas, walaupun Bill Gates sendiri ingin memajukan dunia komputer.Berkat kecerdasan dan kejeniusan yang dimiliki oleh Bill Gates maka di tahun 1975, ia bisa mendapatkan satu tempat di Universitas Harvard yang berada di kota Cambridge, Massachusetts.Namun, kecintaan pada dunia komputer membuat Bill Gates memberanikan diri untuk tidak melanjutkan kuliahnya di Universitas Harvard. Setelah berhenti dari Universitas Harvard, ia memilih untuk memajukan dunia komputer bersama dengan temannya yang bernama Paul Allen.
            </p>
        </p>
        <hr>
        <h4 id="2" class="text-center fw-bold">Steven Paul Jobs</h4>
        <img src="{{ asset("img/stevejobs.jpg") }}" class="img-fluid m-5 rounded mx-auto d-block img-responsive" style="width: 40%" alt="...">
        <p>Memiliki nama asli Steven Paul Jobs, sang genius ini lahir di California, Amerika Serikat pada 24 Februari 1955. Steve Jobs merupakan anak kandung dari pasangan Abdulfattah Jandali dan Joanne Simpson.Ayah Jobs merupakan mahasiswa tamu dari Syria yang kemudian menjadi profesor ilmu politik. Ayahnya juga seorang pemeluk agama Islam.Namun, memiliki masa kecil yang kurang menyenangkan, Steve Jobs lahir dari pasangan di luar nikah. Ketika ia lahir, Jobs bayi diadopsi oleh pasangan Paul dan Clara Jobs yang tinggal di Santa Clara, County, California. Orang tua angkatnya lah yang memberikan nama Steve Jobs. Setelah beberapa tahun, orang tua kandungnya baru menikah dan memberinya adik perempuan bernama Mona Simpson yang kini terkenal sebagai novelis.</p>
        <p>Steve Jobs menghabiskan masa sekolahnya di Cupertino, California, hingga pada tahun 1972, ia lulus dari SMA Homestead dan diterima di Reed College, Portland, Oregon. Akan tetapi, Jobs dikeluarkan (drop out) setelah satu semester. Alasannya hanya karena ia malas mengikuti kelas perkuliahan yang tidak ia sukai.Sejak kecil, Jobs memang berminat sama dunia mekanik berkat ayah angkatnya yang kerap mengajarkan dia cara bongkar-pasang mobil. Selain itu, dengan punya tetangga yang punya bengkel elektronik juga bikin Jobs jatuh cinta sama elektronik. Kembali ke kampusnya, ada satu kelas yang menarik sekali bagi Steve Jobs. Di Reed College ternyata terdapat kelas kaligrafi terbaik di AS. Jobs pun tertarik dan mengikuti kelas itu, tanpa harus jadi mahasiswa.</p>
        <p>Dia belajar seni menulis huruf dan jatuh cinta dengan kaligrafi. Cintanya akan kaligrafi membuat Apple Computers mengeluarkan Macintosh, komputer perusahaan Apple pertama yang punya font, 10 tahun kemudian.Suatu hari, teman sekolah Steve Jobs yang bernama Bill Fernandez, mengenalkan dia sama tetangganya yang merupakan seorang insinyur elektronik lulusan De Anza College. Tetangga Fernandez itu adalah Steve Wozniak. Mereka pun bertemu di garasi rumah Fernandez.Ternyata, saat itu Wozniak sedang membuat proyek personal computer (PC). Merasa cocok dan memiliki banyak kesamaan dalam dunia komputer. Mereka kemudian memutuskan membuat gadget pertama mereka, yaitu Blue Box yang diluncurkan pada tahun 1971. Blue Box merupakan perangkat keras yang memungkinkan orang untuk melakukan telepon jarak jauh secara gratis. Blue Box juga lah yang mengawali penciptaan Apple.Sebelum tahun 1970, komputer-komputer saat itu masih besar-besar, mahal, dan ribet untuk digunakan, serta lebih sering dipakai buat keperluan laboratorium. Dengan berbagai kekurangan komputer purba itu. Steve Jobs melihat peluang uang dari situ</p>
        <p> Jobs tahu kalau Wozniak baru saja membuat desain PC buatannya. Desain itu menyatukan keyboard, monitor, dan komputer dalam satu paket. Dengan mengetik pakai keyboard, tulisan akan muncul langsung di layar. Jobs juga sempat membantu Wozniak dalam membuat chip memori untuk PC rangkaiannya.Jobs pun akhirnya memberi ide kepada Wozniak untuk menjual desain PC-nya. Wozniak pun setuju. Namun, mereka belum memiliki nama untuk PC tersebut. Sampai suatu hari, Steve Jobs pergi ke All One Farm, tempat memetik buah apel kesukaannya. Setelahnya, Wozniak menjemputnya di bandara dan mereka pergi bersama ke Los Altos. Dalam penerbangan itu lah, keduanya memikirkan nama perusahaan mereka. Namun, tidak ada nama yang cocok. Padahal, besok mereka harus mengajukan surat-surat pendirian perusahaan.Kembali dengan idenya yang out of the box. Jobs mengatakan kalau nama Apple cocok untuk perusahaan mereka. Alasannya, karena dia baru saja dari kebun apel dan nama itu terdengar menyenangkan, bersemangat, dan sederhana. Dalam buku telepon pun nama Apple akan ada di atas, dan nama saingan mereka saat itu, Atari ada di bawah. Akhirnya kedua Steve itu mendirikan perusahaan mereka dengan nama Apple Computers pada 1 April 1976. Jobs telah berhasil mendirikan perusahaannya sendiri di usia 21 tahun.10 tahun kemudian, Apple Computers menjadi perusahaan dengan nilai US$2 miliar yang punya lebih dari 4.000 karyawan. Gaya kepemimpinan Steve Jobs lah yang mendorong kesuksesan itu. Jobs terkenal mempunyai triknya sendiri untuk meyakinkan para karyawannya, kalau sesuatu yang kelihatannya mustahil akan bisa jadi kenyataan.</p>
        <hr>
        <h4 id="3" class="text-center fw-bold">Mark Elliot Zuckerberg</h4>
        <img src="{{ asset("img/markelliot.jpg") }}" class="img-fluid m-5 rounded mx-auto d-block img-responsive" style="width: 40%" alt="...">
        <p>Lahir dengan nama lengkap Mark Elliot Zuckerberg sebagai anak kedua dari empat bersaudara dari pasangan Edward Zuckerberg dan Karen Kempner. Ia dibesarkan di New York, Amerika Serikat dalam keluarga yang berkecukupan.Minatnya pada komputerisasi dan pemrograman sudah tampak sejak kecil. Ayahnya bahkan memfasilitasi dengan membelikan komputer ketika berusia 8 tahun. Hingga ketika SMP, ia mampu menciptakan aplikasi plug-in untuk MP3 player Winamp. Mark menikah dengan Priscilla Chan, salah seorang teman kuliahnya sekaligus rekan dalam mengembangkan Facebook. Dari pernikahan tersebut, ia dikaruniai 2 orang anak sepasang yang diberi nama Maxima dan August Chan Zuckerberg.Mark Zuckerberg menempuh pendidikan menengahnya di Phillips Exeter Academy. Di masa ini ia bersama seorang temannya mampu menciptakan aplikasi plug-in yang mampu menghimpun dan membuat playlist lagu berdasarkan kesukaan pengguna.</p>
        <p> Ia pun melanjutkan pendidikan dengan kuliah di Harvard University spesialisasi komputer dan pemrograman. Di sinilah Mark mulai membangun Facebook hingga akhirnya di drop out kampus karena lebih konsentrasi dengan proyek pembuatan aplikasinya. Sejarah Penciptaan Facebookil 1. Membangun Aplikasi Berbasis Media Sosial Bernama Facebook Meski mendapat peringatan dari pihak kampus, ia pun tak kapok dan malah meluncurkan website bernama Facebook. Peluncuran perdananya dilakukan pada Februari 2004. Laman ini merupakan bentuk penyempurnaan dari Facemash.Tujuan tetap sama seperti Facemash. Namun ia menambahkan bahwa Facebook bisa digunakan sebagai alat sosial untuk membuat rekan maupun keluarga dapat saling berkomunikasi lebih efisien, meski terbentang jarak yang luas. Bahkan Facebook menyertakan banyak aplikasi penunjang, setidaknya terdapat 20.000-an.</p>
        <p> Hal tersebut membuat popularitasnya meningkat. Bahkan dikalangan mahasiswa Harvard, aplikasi ini lebih digandrungi daripada MySpace sebagai pendahulunya. 2. Awal Pengembangan Facebook Banyaknya peminat yang menggunakan Facebook, membuat Mark kewalahan. Ia pun menggaet rekannya untuk membantu pengembangan aplikasi. Hingga media sosial ini mampu menjaring 30 kampus dalam waktu singkat.Pengguna Facebook pun semakin bertambah, tak hanya mahasiswa saja. Para siswa menengah dan karyawan perusahaan pun menginginkan bisa menggunakannya. Sehingga dibukalah jejaring yang lebih luas. Hal tersebut lantas membuat Mark semakin sibuk.</p>
        <p> Hingga ia mengabaikan kuliahnya dan di drop out. Kemudian di tahun 2006, Facebook membuka pendaftaran jejaring umum. Dengan hanya berbekal email untuk mendaftar, aplikasi ini pun semakin melesat tajam. 3. Pencapaian Facebook di Awal Pengembangan Setelah dibuka untuk kalangan umum, Facebook digunakan hampir di seluruh pelosok dunia. Awal peluncurannya, aplikasi ini mampu menjaring hingga 6 juta jaringan kelompok pertemanan yang didasarkan pada analisis demografi, pekerjaan, sekolah, kolegial, dan sebagainya.Bahkan dalam sehari, terdapat ratusan juta foto diunggah pada laman Facebook. Karena lalu lintas penggunanya yang tinggi, aplikasi ini lantas menjadi website ke-6 teraktif di dunia. Selain itu juga menjadi media sosial terbesar kedua. 4. Penjualan Saham Facebook Karena dibuka secara umum, jumlah pengguna Facebook sangatlah banyak. Hal ini lantas dimanfaatkan untuk peluang bisnis. Pihaknya pun bekerjasama dengan Accel Partners untuk pembiayaan pengembangan aplikasi.Dana dari investor tersebut digunakan untuk mengganti domain, sehingga berubah menjadi www.facebook.com pada 2005. Facebook juga menggaet kerjasama dengan PayPal untuk pembiayaan pengembangan lainnya. Dana yang terkumpul dari para investor ini, kemudian digunakan untuk semakin memperluas jejaring pengguna Facebook hingga jangkauan internasional. Hal tersebut sukses menggaet banyak anggota baru, bahkan hingga mencapai 5,5 juta pada akhir 2005. 5. Dana Investor yang Melimpah Facebook semakin memperluas jangkauan kerjasama. Ia kemudian menggaet Greylock Partners dan Meritech Capital Partners untuk meluncurkan aplikasinya menjadi berbasis mobile, sehingga lebih ramah digunakan melalui ponsel di mana saja.Investor pun semakin berdatangan, mulai dari Microsoft hingga Li-Ka-Shing. Bahkan beberapa perusahaan internet besar menawarkan diri untuk membeli Facebook. Namun hal ini tidak ditanggapi oleh Mark dan menegaskan hanya membuka kerjasama investasi.</p>
        <hr>
        <h4 id="4" class="text-center fw-bold">Jeffrey Preston Bezos</h4>
        <img src="{{ asset("img/jeff.jpg") }}" class="img-fluid m-5 rounded mx-auto d-block img-responsive" style="width: 40%" alt="...">
        <p>Pendiri Amazon ini memiliki nama lengkap Jeffrey “Jeff” Preston Bezos yang lahir dari pasangan Jacklyn dan Ted Jorgensen di Albuquerque, New Mexico, Amerika Serikat, pada 12 Januari 1964. Sayangnya, kedua orang tuanya bercerai setahun kemudian.Lantas ibunya menikah kembali dengan Miguel Bezos, lantas mengajak mereka pindah ke Houston, Texas, karena ayah tirinya tersebut diangkat menjadi insinyur untuk Exxon. Dari jenjang pendidikan dasar hingga SMA ia habiskan di Houston. Saat SMA, Jeff Bezos mendapat kesempatan mengikuti program pelatihan sains yang diadakan oleh University of Florida.</p>
        <p>Kegiatan tersebut lantas mengantarkannya memperoleh Silver Knight Award pada 1982.Kemudian, setelah menamatkan SMA, Jeff Bezos berencana mendaftarkan kuliah di Princeton University dengan mengambil bidang ilmu fisika.Namun akhirnya ia lebih tertarik pada komputer dan elektro sehingga lulus sebagai sarjana Computer Science and Electrical Engineering. Setelah lulus dari Princeton, dari Biografi Jeff Bezos, dikatakan bahwa ia diterima bekerja di Wall Street dalam bidang ilmu komputer sambil melanjutkan kuliah pascasarjana. Usai mendapat gelar pendidikan yang baru, dia pindah bekerja di Fitel.Pengalaman bekerja pada perusahaan jaringan perdagangan internasional tersebut menjadikan Jeff Bezos bersemangat untuk membangun wirausaha sendiri.</p>
        <p> Keinginannya untuk membangun wirausaha secara mandiri semakin besar kala ia bekerja sebagai Senior Vice President di perusahaan finansial DE Shaw Company. Bahkan atasannya tersebut menggambarkan Jeff Bezos sebagai pengusaha aneh. Mimpinya untuk mendirikan wirausaha mandiri akhirnya terwujud pada tahun 1994 dengan membuka toko buku di garasi rumahnya. Setahun berikutnya ia mulai membangun Amazon.com menjadi toko buku online yang dijalankan dari Seattle, Washington. Pengembangan Amazon 1. Awal Mula Bisnis Biografi Jeff Bezos selanjutnya tentang pencapaiannya dalam mengembangkan Amazon yang awalnya hanya sebuah toko buku online kecil yang dijalankan dari garasi rumah menjadi besar. Bahkan bisa membangun kantor operasional serta 6 gudang untuk inventarisasi buku.Semakin lama Amazon makin terkenal dan merambah pada retail produk lain selain buku.</p>
        <p> Hingga sampai sekarang menjelma menjadi sebuah e-commerce terbesar di dunia. Hal ini lantas menjadikan Bezos semakin menghasilkan banyak kekayaan. 2. Menjadi Orang Terkaya Dunia Pada tahun 2020 ini, Jeff Bezos didaulat sebagai orang terkaya di dunia meskipun sahamnya di Amazon hanya sekitar 25 persen. Jumlah kekayaannya yang dicatat di Forbes mencapai US$ 188,3 milyar atau setara dengan Rp 2,76 triliun.Jeff Bezos termasuk orang yang pantang menyerah dan visioner. Ia selalu membayangkan jika bisnis Amazon tidak dijalankan, maka 6 digit bonus natal tidak akan pernah bisa diperoleh dan penyesalan di hari tua nantinya. 3. Ekspansi Bisnis Amazon Amazon kemudian melebarkan sayapnya dengan merambah sektor yang lainnya. Sebagai langkah awal, ia menjalin kerjasama dengan Blue Origin. Juga melakukan ekspansi dengan mengakuisisi media Washington Post, memiliki ekspedisi Bezos Expeditions, serta investasi di bidang kesehatan. Amazon kini juga mengembangkan retail yang terhubung dengan aplikasi dimana pengunjung bisa melakukan belanja secara mandiri tanpa ada yang melayani dan tidak ada kasir. Toko dipasangi dengan cctv.Sistem tersebut menggunakan pembayaran yang terhubung dengan aplikasi Amazon. Jadi, jika pembeli telah selesai belanja, barang-barang yang dipilihnya harus di scan kemudian total yang harus dibayarkan akan memotong secara otomatis saldo uang digital.</p>
        <hr>
        <h4 id="5" class="text-center fw-bold">Sir Timothy Jhon Berners-Lee</h4>
        <img src="{{ asset("img/bernes.jpeg") }}" class="img-fluid m-5 rounded mx-auto d-block img-responsive" style="width: 40%" alt="...">
        <p>Tim Berners-Lee. Bernama lengkap Sir Timothy John “Tim” Berners-Lee. Ia lahir di London, Inggris, 8 Juni 1955 dikenal sebagai penemu World Wide Web dan ketua World Wide Web Consortium, yang mengatur perkembangannya. Dialah ilmuwan komputer yang menemukan dan mengembangkan jaringan global maya atau www. Berners Lee adalah penulis program browser pertama dan server WWW pertama di dunia. Saat ini, browser yang sering digunakan adalah Internet Explorer, Netscape dan Mozilla. Berners-Lee juga menulis piranti lunak yang mendefinisikan Hyper Text Markup Language (HTML), Uniform Resource Locator (URL), dan Hyper Text Transfer Protocol (HTTP). Sewaktu masa kanak-kanak, Tim bersekolah di Sheen Mount Primary School.</p>
        <p> Kemudian, mulai 1969 sampai 1973, Tim menempuh pendidikan di Emanuel School, Battersea. Sejak usia belia, dia sudah menyukai segala hal berbau teknologi. Misalnya, bermain dengan model kereta api dan belajar tentang elektronik.Setelah lulus dari Emanuel School, Timothy melanjutkan ke Queen’s College di Oxford pada 1973 sampai 1976. Dia lulus dan meraih gelar sarjana di bidang fisika. Berners-Lee pernah membuat sebuah komputer dari televisi tua yang dibelinya di toko reparasi selama masa perkuliahan.Pada 1990, Timothy menikah dengan Nancy Carlson, seorang pemrogram komputer asal Amerika Serikat. Nancy juga bekerja di WHO (World Health Organization) di Swiss. Keduanya memiliki dua anak, sebelum akhirnya bercerai pada 2011.Lalu, di 2014, Berners-Lee menikahi Rosemary Leith, seorang entrepreneur internet dan perbankan asal Kanada.</p>
        <p> Berners-Lee menjadi profesor di Sekolah Teknik, sekaligus berada dalam Departemen Teknik Elektro dan Ilmu Komputer di laboratorium Computer Science and Artificial Intelligence (CSAIL). Tak hanya itu, Tim juga nenjadi profesor di Departemen Elektro dan Ilmu Komputer di Universitas Southampton.Pada 2001, Berners-Lee menjadi bagian dari “Fellow of the Royal Society”. Dia juga sudah menerima beberapa penghargaan internasional. Berners-Lee memperoleh gelar kesatria dari Ratu Elizabeth pada 2014 serta diberi penghargaan “Order of Merit” pada 2007.</p>
        <p> Penemuan Tim Barners-Lee :</p>
        <ul>
            <li>WWW (World Wide Web)</li>
            <p>Penemuan paling terkenal dari Berners-Lee adalah World Wide Web. WWW ditemukan pada 1989 di CERN dan awalnya difungsikan sebagai automasi pembagian informasi antara ilmuwan-ilmuwan di berbagai universitas dan institut di seluruh dunia. Ide dasar dari WWW adalah penggabungan teknologi komputer, data jaringan, dan hiperteks ke dalam sebuah sistem informasi global yang mudah dan andal.</p>
            <li>HTML (Hypertext Markup Languange)</li>
            <p>HTML merupakan bahasa resmi dari World Wide Web. Versi pertama dari HTML dituliskan oleh Tim pada 1993. Namun, dia telah menuliskan proposalnya di tahun 1989. Pada 1990, Tim menciptakan bahasa HTML bersama dengan peramban dan peranti lunak server.</p>
            <li>HTTP (Hypertext Transfer Protocol)</li>
            <p>HTTP didesain oleh Berners-Lee untuk mendukung adopsi ide World Wide Web. Spesifikasi ini merupakan bahasa umum dari server dan klien yanh saat ini menjadi standar dari web modern. Berawal dari kata kunci simpel dan jalur dokumen, HTTP tidak hanya menjadi pilihan protokol untuk peramban, tetapi juga perangkat keras dan lunak yang terkoneksi dengan internet.</p>
            <li>URL (Uniform Resource Identifier)</li>
            <p>Tim menciptakan URL pada 1994. Sederhananya, URL adakah sebuah alamat untuk web. URL menjadi salah satu bagian penting dari WWW.
                </p>
        </ul>
        <hr>
        <h4 id="6" class="text-center fw-bold">Lawrence Edward Page</h4>
        <img src="{{ asset("img/larry.jpg") }}" class="img-fluid m-5 rounded mx-auto d-block img-responsive" style="width: 40%" alt="...">
        <p>Berdasarkan buku Sergey Brin and Larry Page: Founders of Google, Larry Page lahir di Lansing, Michigan pada 26 Maret 1973. Kedua orang tuanya bernama Carl Vincent dan Gloria Page. Mereka merupakan merupakan insinyur komputer. Larry Page memiliki kakak laki-laki bernama Carl Jr. dan adik perempuan bernama Beverly. Orang tua mereka bercerai saat Larry berusia delapan tahun. Meski demikian, masa kecil Larry dipenuhi banyak hal gembira. Saat Larry masih kecil, keluarganya sudah memiliki komputer. Padahal, komputer untuk rumah tangga saat itu masih tergolong langka. Komputer pertama keluarga Larry mereka dapatkan pada 1978. Larry Page bersekolah di sekolah dasar dengan metode Montessori, yaitu metode pendidikan yang berbasis pada aktivitas mandiri, pembelajaran langsung, dan permainan kolaboratif.</p>
        <p> Sekolah tersebut mengizinkan Larry untuk mengeksplorasi berbagai minat dan belajar dengan caranya sendiri. Di rumah, pengaruh kedua orang tuanya dan ketersediaan komputer membuatnya tertarik menekuni bidang komputer. Saat menduduki bangku sekolah dasar, Larry menjadi anak pertama di sekolahnya yang menulis makalah menggunakan perangkat pengolah kata. Selain menekuni komputer, Larry juga senang membaca majalah Popular Science dan jurnal-jurnal lain di drumahnya. Kakaknya, Carl Jr., bersekolah di University of Michigan. Ia sering membahas tugas tentang komputer bersama Larry. Selain menekuni bidang komputer, Larry juga tertarik dengan musik. Ia bermain saksofon bersama band sekolah saat ia bersekolah di Lansing High School. Setelah lulus SMA, Larry berkuliah di University of Michigan, seperti kedua orang tuanya. Larry meraih gelar Sarjana Sains di bidang teknik komputer.</p>
        <p>Kemudian ia melanjutkan kuliah pascasarjana di Stanford University dan meraih gelar Magister Sains di bidang ilmu komputer. Larry bertemu Sergey Brin saat bersekolah di Stanford University. Mereka membangun mesin pencari yang menggunakan tautan untuk menentukan pentingnya halaman individual di World Wide Web. Mesin pencari tersebut dinamakan Backrub. Setelah berdiskusi, nama Backrub diubah menjadi Google yang terinspirasi dari kata googol yang merujuk pada bilangan setara dengan sepuluh dipangkatkan seratus. Situs web Google.com diregistrasikan ke dalam World Wide Web pada 1997. Selama beberapa tahun ke depan, Google menarik perhatian civitas akademika dan investor. Melansir Google, pada Agustus 1998, Andy Bechtolsheim menulis cek kepada Larry dan Sergey sebesar US$ 100.000 dan Google Inc. secara resmi didirikan. Suntikan dana tersebut berhasil membantu tim Larry dan Sergey untuk mendirikan kantor di sebuah garasi di Menlo Park, California. Google terus berkembang hingga mampu mendirikan kantor pusat di Mountain View, California.</p>
        <hr>
        <h4 id="7" class="text-center fw-bold">Martin Cooper</h4>
        <img src="{{ asset("img/martincooper.jpeg") }}" class="img-fluid m-5 rounded mx-auto d-block img-responsive" style="width: 40%" alt="...">
        <p>Martin Marty Cooper lahir 26 Desember 1928 di Chicago, Illinois, AS yang merupakan pemimpin tim insinyur dari Motorola yang mengembangkan perangkat genggam seluler yang berbeda dari telepon mobil (Car Phone).Cooper adalah CEO dan pendiri ArrayComm, sebuah perusahaan yang bekerja di bidang penelitian teknologi Smart Antenna dan pengembangan jaringan nirkabel, dan direktur Penelitian dan Pengembangan untuk Motorola. Martin Cooper dibesarkan di Chicago selama resesi dunia. Orang tuanya adalah imigran Ukraina. Beliau memperoleh gelar sarjana di bidang Teknik Elektro pada tahun 1950. Martin Cooper bergabung dengan Korps Pelatihan Perwira Cadangan Angkatan Laut Amerika Serikat.</p>
        <p> Dia bertugas di kapal perusak Angkatan Laut AS selama Perang Korea dan kemudian di kapal selam yang berbasis di Hawaii. Setelah perang, Cooper meninggalkan angkatan laut dan mulai bekerja untuk Teletype, anak Western Electric. Pada tahun 1954, ia pindah ke Motorola. Selama bekerja di sana ia melanjutkan studinya pada malam hari.Pada tahun 1957, ia menerima gelar Master di bidang teknik elektronik dari Institut Teknologi Illinois. Pada tahun 1960 ia berperan penting dalam mengubah lembaran teknologi informasi yang sebelumnya terbatas digunakan dalam satu gedung menjadi lebih luas yang dapat menghubungkan antar kota. Pada tahun 1960, John F. Mitchell menjadi chief engineer proyek komunikasi portabel Motorola.</p>
        <p>Pada awal 1970-an, Mitchell memberi Cooper tanggung jawab untuk divisi telepon mobil.Mitchell dan Cooper membayangkan alat komunikasi yang tidak hanya terjebak di dalam mobil. Jadi alatnya harus kecil dan cukup ringan untuk dibawa-bawa. Butuh 90 hari pada tahun 1972 untuk membuat prototipe pertama dari ide tersebut. Cooper dan para insinyur yang bekerja untuknya, serta Mitchell mematenkan penemuan "Sistem Telepon Radio" yang diajukan pada 17 Oktober 1973 dengan nomor paten 3906166 dan disetujui pada September 1975 atas nama mereka. Cooper dianggap sebagai penemu telepon seluler (ponsel) pertama dan orang pertama yang melakukan panggilan dengan prototipe telepon seluler pada 3 April 1973. Pada tahun 1983, setelah bertahun-tahun pengembangan lebih lanjut, Motorola memperkenalkan ponsel portabel pertama untuk konsumen, DynaTAC 8000x.</p>
        <p> Meskipun memiliki harga tinggi, ponsel ini sukses. Pada tahun yang sama 1983, Cooper meninggalkan Motorola dan mendirikan Cellular Business Systems, Inc. (CBSI), yang menjadi perusahaan terkemuka dalam penagihan layanan telepon seluler. Pada tahun 1986 ia dan rekan-rekannya menjual CBSI ke Cincinnati Bell seharga $ 23 juta, dan ia dan istrinya, Arlene Harris, mendirikan Dyna, LLC. Dyna berfungsi sebagai organisasi pusat dari mana mereka meluncurkan perusahaan lain, seperti ArrayComm (1996), yang mengembangkan perangkat lunak untuk sistem nirkabel, dan GreatCall (2006), yang menyediakan layanan nirkabel untuk Jitterbug, sebuah ponsel dengan fitur sederhana yang dimaksudkan untuk tua. Cooper menerima hadiah Drapper Charles Stark dari Akademi Teknik Nasional pada 2013.</p>
        <hr>
        <h4 id="8" class="text-center fw-bold">Kevin David Mitnick</h4>
        <img src="{{ asset("img/kevindavid.jpeg") }}" class="img-fluid m-5 rounded mx-auto d-block img-responsive" style="width: 40%" alt="...">
        <p>Nama lengkapnya adalah kevin David Mitnick yang kemudian dikenal dengan nama Kevin Mitnick. Dalam dunia komputer, ia dikenal dengan nama The Condor. Ia dilahirkan pada tanggal 6 Agustus 1963. Kala itu hanya orang yang cukup berada yang dapat memiliki komputer. Kevin Mitnick sendiri belajar dan mengenal komputer ketiika ia bekerja di toko radishack serta perpustakaan umum yang menyediakan komputer. Ia menghabiskan sebagian besar waktunya mempelajari sistem komputer. Tak mengherankan bila di usia muda ia sudah paham bagaimana sistem dan jaringan komputer bekerja. Pada usia 12 tahun, Mitnick menggunakan tehnik Social Engineering atau rekayasa sosial untuk melewati sistem kartu tiket yang digunakan dalam sistem bus Los Angeles dengan cara meyakinkan supir bus.</p>
        <p>Ia pertama kali melakukan kejahatan komputer saat berusia 16 tahun pada tahun 1979. Kevin Mitnick menggunakan pengetahuannya tentang komputer dengan membobol jaringan komputer Digital Equipment Corporation (DEC) dan membajak perangkat lunak sistem operasi RSTS/E milik perusahaan. Aksinya ini membuat ia pertama kali dijatuhi hukuman selama 12 bulan penjara. Setelah bebas, ia kembali melakukan peretasan pada komputer COSMOS (Computer System Mainstrem Operation) yang berfungsi sebagai sentral database telepon Amerika milik perusahaan telepon Pasific Bell yang berbasis di Log Angeles. Akibat perbuatannya itu, Kevin Mitnick harus meringkuk di penjara.</p>
        <p>Setelah bebas dari penjara, ia kembali melakukan aksi kejahatan komputernya. Kali ini tidak tanggung-tanggung, ia melakukan peretasan atau hacking di jaringan komputer di Pentagon, Departemen Pertahanan Amerika. Setelah terbebas dari penjara, Kevin Mitnick kembali mencoba hidup normal. Ia memiliki bekerja pada perusahaan mailing list di wilayah Las vegas, Amerika Serikat. Namun penyakitnya kembali kambuh. Biro Keamanan Amerika yakni FBI mencurigai Kevin melakukan peretasan sistem komputer Tel Tec Detective. Akibatnya Kevin kemudian melarikan diri dari kejaran polisi. Dan saat itu FBI menetapkan Kevin Mitnick dalam daftar buronan hacker nomor satu yang paling dicari atau The Most Wanted Hacker. Selama menjadi buronan hacker paling dicari FBI, kevin Mitnick hidup secara berpindah-pindah dari satu wilayah ke wilayah lain.</p>
        <p> Disini kejahatan komputernya semakin menjadi. Diketahui ia membobol sistem komputer perusahaan besar seperti Fujitsu, Motorola dan Nokia. Menurut Departemen Kehakiman AS, Mitnick memperoleh akses ilegal ke puluhan jaringan komputer saat dia menjadi buronan. Dia menggunakan telepon seluler yang dikloning untuk menyembunyikan lokasinya.Ia juga menyalin perangkat lunak berharga dari beberapa perusahaan telepon seluler dan komputer terbesar di negara itu. Selain itu, Mitnick juga menyadap dan mencuri ratusan kata sandi komputer, mengubah jaringan komputer, dan membobol serta membaca email pribadi. Dalam pelariannya, Kevin Mitnick membobol layanan penyimpanan rekening seseorang. Layanan tersebut menginformasikan kepada pemilik rekening bahwa rekeningnya sudah over quota. Disinilah kelalaian Mitnick. Sebelum ditangkap, Mitnick sedang melacak balik orang yang sedang mengejarnya yaitu Tsutomu Shimomura. Tapi pada saat yang bersamaan FBI yang sudah melacak keberadaan Mitnick datang dan menjadi “tamu” tak diundang di rumah pelarian Kevin Mitnick. Kali ini pengadilan menjatuhkan hukuman kepada Kevin Mitnick selama 5 tahun penjara. Pada tahun 2000, Kevin Mitnick bebas dari penjara. Namun ia dilarang memegang atau berhubungan dengan komputer. Dua tahun setelah pembebasannya, Ia akhirnya diperbolehkan menggunakan komputer namun dengan syarat tanpa jaringan internet. Baru pada tahun 2003, ia akhirnya bisa menggunakan jaringan komputer. Kevin Mitnick juga mendirikan perusahaan konsultan keamanan komputer yang bernama Mitnick Security Consulting. Ia juga memiliki website yang beralamat di kevinmitnick.com.</p>
        <hr>
        <h4 id="9" class="text-center fw-bold">Linus Benedist Torvalds</h4>
        <img src="{{ asset("img/linustorvalds.jpg") }}" class="img-fluid m-5 rounded mx-auto d-block img-responsive" style="width: 40%" alt="...">
        <p>Linus Benedict Torvalds (lahir di Helsinki, Finlandia, 28 Desember 1969) adalah rekayasawan perangkat lunak Finlandia yang dikenal sbg perintis pengembangan Kernel Linux. Beliau sekarang bertindak sbg koordinator proyek tersebut.Linux terinsipirasi oleh Minix (sistem operasi yang dikembangkan oleh Andrew S. Tanenbaum) sebagai mengembangkan sistem operasi mirip-Unix (Unix-like) yang mampu dijalankan pada suatu PC. Linux sekarang mampu dijalankan pada berbagai arsitektur pautan. Ketika Linus Torvalds, seorang mahasiswa Finlandia pendiam membagi-bagikan kode sumber (source code) kernel Linux seukuran disket via internet pada tahun 1991, beliau sama sekali tidak menduga bahwa apa yang dimulainya melahirkan suatu bisnis berharga miliaran dolar di kemudian hari.Beliau bahkan tidak menduga Linux kemudian menjadi sistem operasi paling menjanjikan, yang dapat dibenamkan ke dalam server, komputer desktop, tablet PC, PDA, handphone, GPS, robot, mobil sampai pesawat ulang alik buatan NASA.</p>
        <p>Tidak hanya itu, banyak maniak Linux (Linuxer) yang melakukan pembelian perangkat buatan Apple dan mengganti sistem operasinya dengan Linux. Untuk saya itu sedikit gila, mengingat menghapus sistem operasi Mac & iPod berfaedah membuang duit dan menggantinya sistem operasinya cukup sulit dibanding desktop berbasis Windows. Masa ini 20% pangsa pasar desktop di seluruh dunia menggunakan Linux jauh di atas Mac OS dan terus mengejar OS Windows. Dan 12,7% server di seluruh dunia menggunakan Linux, jauh di atas UNIX, BSD, Solaris, dan terus meningkat menggerus pangsa pasar server Microsoft. Masa ini Linus meninggalkan posisi menjanjikan di perusahaan semi konduktor Transmeta dan tinggal bersama istri dan 3 anaknya di suatu bukit di desa di Portland, Oregon, USA, berdekatan dengan markas Open Source Development Labs.</p>
        <p>Linus bukan orang pertama yang membagi-bagikan source code karena pola ini adalah hal yang biasa pada masa awal tumbuhnya industri computer. Tapi Linus sukses menetapkan standar yang memaksa banyak pengembang ikut membebaskan kode sumber program mereka, mulai dari BSD, Solaris, Suse, Java sampai Adobe. Meski hanya bergaji ratusan ribu dolar pertahun, Linus telah menciptakan banyak multimilyuner dalam industri komputer mulai dari RedHat, Suse, Debian, Mandriva, Ubuntu dan banyak developer software open source pautannya. Hampir tak hadir yang berubah dari Linus. Ketika beliau datang terlambat di suatu konferensi IT, beliau bahkan tak segan-segan duduk di lantai dengan celana pendek dan sepatu-sandal kesukaannya. Beliau bahkan tidak marah tatkala memberikan pidato di mimbar dan diinterupsi oleh beberapa programmer BSD yang maju ke depan panggung yang mengklaim bahwa kernel BSD jauh lebih hebat ketimbang kernel Linux.</p>
        <p>Beliau bahkan tidak segan-segan memakai T-Shirt BSD yang disodorkan pemrotes dan melanjutkan pidatonya. Menurut Linus, apa yang dilakukannya hanyalah sebagai berbagi. Beda dengan Richard M Stallman yang fanatik dengan konsep free software, Linus hanya menekankan sisi keterbukaan (open), tak peduli apakah kemudian dalam suatu sistem operasi bercampur program free dan proprietery.Setiap kata-kata Linus hampir menjadi sabda di kalangan Linuxer yang menciptakan standar nilai tertentu. Setiap publikasi, pidato, email dab press releasenya selalu ditunggu-tunggu jutaan orang. Di sela kesibukannya, Linus menyempatkan diri bersepeda menuruni bukit dan minum di bar desa. Pada 24 April 2012, Linus terpilih sbg salah satu dari dua penerima penghargaan Millennium Technology Prize 2012, suatu penganugerahan sekelas penghargaan Nobel di dunia teknologi.</p>
        <hr>
        <h4 id="10" class="text-center fw-bold">Elon Reeve Musk</h4>
        <img src="{{ asset("img/elonmusk.jpeg") }}" class="img-fluid m-5 rounded mx-auto d-block img-responsive" style="width: 40%" alt="...">
        <p>Elon Reeve Musk atau yang lebih dikenal sebagai Elon Musk lahir di Pretoria, Afrika Selatan pada 28 Juni 1971. Mengutip dari tirto.id, disebutkan bahwa Elon Musk merupakan pebisnis, penemu, dan industrialis Amerika Serikat. Musk pernah menempuh pendidikan di Pretoria Boys High School. Kemudian pindah ke Kanada saat berusia 17 tahun untuk menghindari wajib militer di Afrika Selatan. Di tahun 1992, selepas belajar selama dua tahun di Queen’s University, Kingston, Ontario, Elon Musk pindah Wharton School di University of Pennsylvania dan mendapatkan gelar di bidang ekonomi dan di bidang fisika. Setelah itu, ia pindah ke California untuk mengejar gelar Ph.D dalam bidang fisika terapan di Stanford, namun akhirnya keluar. Keputusannya keluar dari Stanford, karena ingin mengejar mimpinya untuk berwirausaha di sektor internet, energi terbarukan, dan luar angkasa.</p>
        <p>Elon Musk kini dikenal sebagai pebisnis sukses dengan berbagai usaha yang mendunia. Adapun beberapa perusahaan milik Elon Musk, sebagai berikut:</p>
        <ul>
            <li>Zip2 Di awal karirnya sebagai pengusaha, Elon Musk mendirikan Zip2 yang merupakan perusahaan perangkat lunak atau software. Perusahaan ini ia dirikan bersama adiknya, Kimbal Musk. Perusahaan ini mengembangkan dan memasarkan “panduan kota” internet untuk industri penerbitan surat kabar.</li>
            <li>• X.com dan PayPal Hasil penjualan dari Zip2, kemudian ia gunakan untuk mendirikan perusahaan layanan keuangan bernama X.com pada Maret 1999. Musk merekrut eksekutif bisnsi John Story dan Bill Harris sebagai investor. Haris juga menjabat sebagai Presiden dan CEO perusahaan tersebut.</li>
            <li>SpaceX Perusahaan ketiga yang didirikan oleh Elon Musk yaitu Space Exploration Technologies Corporation atau SpaceX, yang merupakan perusahaan teknologi dirgantara asal Amerika Serikat (AS). Perusahaan didirikan pada 6 Mei 2022. perusahaan SpaceX ini dikabarkan akan bekerja sama dengan PT. Telkom Indonesia. Kerja sama ini berkaitan dengan pemanfaatan staelit untuk jasa komunikasi. SpaceX masuk dalam kerjasama ini lewat anak usahanya, Starlink. Perusahaan tersebut bergerak dalam infrastruktur internet.</li>
            <li>Tesla Inc. Tesla Inc merupakan salah satu perusahaan produsen mobil listrik. Elon Musk kini menjadi pendiri sekaligus CEO Tesla. Elon Musk diketahui mempunyai 21% saham perusahaan dan kekayaan bertambah seiring dengan naiknya nilai saham Tesla. Selain empat perusahaan yang telah disebutkan, Elon Musk sebenarnya masih memiliki beberapa perusahaan yang bergerak di berbagai bidang. Terbaru, Elon Musk diketahui membeli media sosial Twitter.</li>
        </ul>
        <hr>
        <h4 id="11" class="text-center fw-bold">Jack Ma</h4>
        <img src="{{ asset("img/jack.jpg") }}" class="img-fluid m-5 rounded mx-auto d-block img-responsive" style="width: 40%" alt="...">
        <p>Jack Ma atau Ma Yun lahir di Hangzhou, Provinsi Zhejiang, China pada tanggal 15 oktober 1964. Jack Ma tumbuh di lingkungan penduduk yang sederhana di Hangzhou pada 1980-an. Saat itu, China baru membuka diri terhadap bangsa barat. Semasa hidupnya, dia harus berhadapan dengan berbagai masalah.Ma ditolak di setiap sekolah, tempat dia ingin belajar. Bahkan sejak sekolah dasar, dia sudah menerima penolakan karena ujian matematikanya yang tak begitu baik. Tapi Ma bertahan dan melaluinya. Sejak usia 12 hingga 20 tahun, dia mengendarai sepedanya selama 40 menit ke hotel di mana dia dapat belajar bahasa Inggris. Delapan tahun bergaul bersama banyak turis asing benar-benar mengubah cara pandangnya mengenai hidup.</p>
        <p>Ma merasa dirinya berpikir lebih global dibandingkan kebanyakan penduduk China lain. Apa yang diceritakan para turis sangat berbeda dengan semua yang dipelajari Ma dari para guru dan buku di sekolah. Ma pertama kali menggunakan internet pada 1995 saat dia mencari kata `beer` dan `China`. Tapi saat itu, Ma tidak menemukan hasil pencarian yang diharapkan melalui internet. Berbekal rasa penasaran, dia lantas menciptakan laman website untuk jasa terjemahan bahasa China dengan seorang teman. Hanya dalam beberapa jam saja, dia menerima banyak surat elektronik (email) yang cukup membantunya membangun situs tersebut. Mendirikan Alibaba.com.Kejadian itulah yang kemudian menjadi faktor pemicu berdirinya Alibaba Group empat tahun kemudian.</p>
        <p> Kini, alibaba merupakan retailer online terbesar di China dan berada di posisi kedua dunia setelah Wal-Mart. Dia bahkan mengawali karirnya hanya sebagai guru bahasa Inggris. Meski demikian, perannya di Alibaba selalu menempati posisi strategis utama. Situs pertamanya, Alibaba.com, merupakan tempat pertama yang menghubungkan para eksportir China dengan para pembeli di luar negeri. Perusahaannya juga mampu dengan cepat menarik para investor. Saat ini, Alibaba tengah berniat mengalahkan eBay, situs jual beli online yang bermarkas di Amerika Serikat (AS). Berkat kegigihannya, dua situs Alibaba, Taobao Marketplace dan Tmall.com, kini mendominasi sistem portal pengiriman China.</p>
        <p> Tanpa berbekal pengetahuan sedikitpun di bidang teknologi dan komputerisasi, Jack Ma ternyata mampu menjadi pendiri retailer online terbesar di China, Alibaba Group. Berkat bisnisnya itulah, mantan guru bahasa Inggris ini sukses menjadi salah satu miliarder terkaya di dunia. Banyak pengusaha yang menjulukinya sebagai `Crazy Jack` karena ide-ide bisnis super gila dan fantastis yang dilontarkannya. Tak ada satupun yang yakin, Jack dapat mewujudkan seluruh ide bisnisnya tersebut. Dibandingkan berbicara soal kehebatan perusahaan, dia lebih senang membahas bagaimana Alibaba dapat membantu banyak konsumen, menciptakan lapangan kerja dan melayani masyarakat.Di AS, Ma menemukan mimpinya. Dia berkunjung ke Sillicon Valley melihat banyak mobil lalu lalang dan bangunan super megah. Di situlah dia menemukan semangat juangnya untuk menjadi pria sukses. IPO Alibaba.com dan menjadi milyarder nomor satu di China Pada Agustus 2014, Jack Ma sebenarnya telah menyandang gelar sebagai miliarder terkaya di China.Kala itu, harta Ma diprediksi akan meroket saat Alibaba melepas saham perdananya di AS. Benar saja, IPO yang digelar Alibaba di bursa saham New York akhir pekan lalu mencetak angka fantastis dan mencetak rekor dunia.Berkat nilai saham yang melonjak hingga 38 persen, harta kekayaan Ma kini bertambah hingga menjadi US$ 26,5 miliar. Dia menjadi orang terkaya di China dan menempati posisi ke-23 di jajaran miliarder dunia.Beberapa miliarder lain mengatakan, itu baru permulaan, harga saham Alibaba masih akan terus melesat dan mengucurkan pundi-pundi uang lebih banyak ke kantong Ma. Semangat di diri Ma, telah mengubah pria muda yang ditolak sekolah dan puluhan perusahaan menjadi salah satu miliarder terkaya di dunia.</p>
        <hr>
        <h4 id="12" class="text-center fw-bold">Walter Elian Disney</h4>
        <img src="{{ asset("img/walt.jpg") }}" class="img-fluid m-5 rounded mx-auto d-block img-responsive" style="width: 40%" alt="...">
        <p>Lahir di Chicago, Illinois, pada 5 Desember 1901 dengan nama lengkap Walter Elias Disney, dia merupakan putra keempat dari seorang tukang kayu, petani, sekaligus kontraktor bangunan, Elias Disney. Ibunya, Flora Call, merupakan seorang guru sekolah negeri. Saat masih balita, Disney dan keluarganya pindah ke sebuah pertanian di dekat Marceline, Missouri.Walt cilik kemudian mulai bersekolah.</p>
        <p>Dari situlah, dia menunjukkan bakatnya dalam menggambar dan melukis dengan krayon dan cat air. Ayahnya meninggalkan usaha pertaniannya dan memindahkan keluarganya ke Kansas City pada 1911.Pada musim panas, Disney kerap mengambil pekerjaan sambilan seperti berjualan kudapan dan koran kepada penumpang kereta api.Pamannya, Mike Martin, merupakan seorang ahli mesin yang bekerja di perusahaan kereta api. Disney menempuh pendidikan di SMA McKinley, Chicago. Dia mengambil kelas menggambar dan fotografi. Dia juga menjadi kartunis yang berkontribusi untuk koran sekolah.</p>
        <p>Pada malam hari, dia ikut kursus di Institut Seni Chicago. Dia putus sekolah pada usia 16 tahun untuk bergabung dengan Angkatan Darat pada Perang Dunia I, namun ditolak karena masih di bawah umur. Kemudian, dia diterima Palang Merah dan dikirim ke Perancis selama satu tahun untuk mengemudikan ambulans. Dia kembali ke AS pada 1919. Kembali ke Kansas City, dia bekerja sebagai juru gambar dan pewarnaan di sebuah studio seni komersial. Dia bertemu dengan Ub Iwerks, seorang seniman muda yang berkontribusi besar terhadap kesuksesan awal Disney.</p>
        <p>Keduanya kemudian memulai sebuah bisnis studio animasi kecil pada 1922. Mereka membuat sketsa kartun animasi hitam putih dengan iringan musik, berjudul Laugh-O-grams. Selain itu, film kisah peri berdurasi 7 menit berjudul Alice in Cartoonland, yang menggabungkan live action dan animasi. Namun, seorang distributor film di New York menipu kedua produser muda itu, dan Disney terpaksa mengajukan kebangkrutan pada 1923. Pindah ke California, bersama saudara laki-lakinya, Roy, memproduksi kartun serial Alice. Berkolaborasi dengan Iwerks, dia bereksperimen menciptakan karakter baru, seekor tikus yang ceria, bersemangat, dan nakal, bernama Mickey.</p>
        <p>Mickey Mouse memulai debutnya pada 1928 dalam film berjudul Steamboat Willie. Selama lima tahun berikutnya, Walt Disney Studios menyelesaikan serangkaian film animasi panjang seperti Pinocchio (1940), Fantasia (1940), Dumbo (1941), dan Bambi (1942). Pada 1941, perusahaan itu sempat mengalami kemunduran akibat aksi mogok dan pengunduran diri para animator. Disney terus memproduksi film animasi terkenal lainnya, seperti Cinderella (1950), Treasure Island (1950), Alice in Wonderland (1951), Peter Pan (1953), Lady and the Tramp (1955), Sleeping Beauty (1959) dan 101 Dalmatians (1961). Secara keseluruhan, lebih dari 100 film diproduksi oleh studionya. Disney kemudian mulai memasuki acara hiburan di televisi. Pada awal 1950-an, Disney merancang sebuah taman hiburan besar Disneyland yang akan dibangun di dekat Los Angeles.</p>
        <p>Taman hiburan Disneyland bernilai 17 juta dollar AS resmi buka pada 17 Juli 1955 di Anaheim, California. Selanjutnya, Disney merencanakan taman hiburan baru di Florida. Ketika masih dalam tahap pembangunan pada 1966, Disney didiagnosis menderita kanker paru-paru. Disney meninggal dunia pada 15 Desember 1966 pada usia 65 tahun. Dia dikremasi dan abunya dikebumikan di Forest Lawn Cemetery, di Los Angeles, California. Setelah kematian saudaranya, Roy melanjutkan rencana penyelesaian pembangunan taman hiburan Florida yang dibuka pada 1972 dengan nama Walt Disney World. Disney merupakan peraih Academy Awards terbanyak dengan memenangkan 22 piala Oscar dan masuk dalam 59 nominasi. Disney memiliki istri bernama Lilian, yang juga berkecimpung dalam dunia animasi. Lilian meninggal dunia pada 16 Desember 1997.
        </p>
        <hr>
        <h4 id="13" class="text-center fw-bold">Dennis MacAlistair Ritchie</h4>
        <img src="{{ asset("img/dennis.jpg") }}" class="img-fluid m-5 rounded mx-auto d-block img-responsive" style="width: 40%" alt="...">
        <p>Dennis MacAlistair Ritchie (kelahiran 9 September 1941 – meninggal 12 Oktober 2011 pada umur 70 tahun)adalah seorang ilmuwan komputer yang dikenal atas sumbangsihnya menciptakan bahasa pemrograman C dan berbagai sistem operasi seperti Multics dan Unix. Ritchie menerima penghargaan Turing Award pada tahun 1983 dan National Medal of Technology 1998 pada 21 April 1999. Ia menjabat sebagai kepala Departemen Riset Perangkat lunak Sistem di Lucent Technologies saat pensiun pada tahun 2007.Ritchie kelahiran di Bronxville, New York. Pendidikan sarjana diraihnya dari Harvard di segi fisika dan matematika terapan. Pada tahun 1967, Ritchie mulai bekerja di Bell Labs' Computing Sciences Research Center, kesudahan di Lucent Technologies hingga ia pensiun pada tahun 2007.</p>
        <p>Pada tahun 1968, Ritchie mendapatkan gelar doktor Ph.D. dari Harvard.[4] Ritchie (bersama Ken Thompson) menerima penghargaan Turing Award pada tahun 1983 dan National Medal of Technology 1998 pada 21 April 1999. Pada tahun 1988, Ritchie terpilih menjadi anggota National Academy of Engineering atas jasanya dalam "development of the 'C' programming language and for co-development of the UNIX operating system.Ritchie dikenal sebagai pembuat bahasa pemrograman C, pengembang utama sistem operasi, dan sebagai salah satu dari penulis (bersama Brian Kernighan) buku "kamus bahasa C," The C Programming Language. Penemuan bahasa C dan pengembangan Unix menjadikan Ricthie dan Ken Thompson sebagai pionir utama dunia komputasi modern.</p>
        <p>Bahasa C hingga sekarang masih digunakan secara luas dalam program aplikasi, sistem operasi, pengembangan sistem benam, dan pengaruhnya dalam bahasa pemrograman modern lain. Sedangkan Unix juga telah memberikan pengaruh akbar, mendirikan konsep dan prinsip dalam dunia komputasi masa sekarang. Penghargaan yang Ritchie dapatkan:</p>
        <ul>
            <li>Pada tahun 1983, Ritchie bersama Ken Thompson menerima penghargaan Turing Award atas jasa mereka dalam pengembangan teori sistem operasi dan khususnya atas implementasi sistem operasi Unix. Pada kesempatan tersebut, Ritchie memberikan kuliah yang berjudul "Reflections on Software Research".</li>
            <li>IEEE Richard W. Hamming Medal Pada tahun 1990, Ritchi dan Ken Thompson menerima IEEE Richard W. Hamming Medal dari Institute of Electrical and Electronics Engineers (IEEE), "sebagai penggagas sistem operasi UNIX dan bahasa pemrograman C".</li>
            <li>National Medal of Technology Pada 21 April 1992, Ritchie dan Ken Thompson menerima National Medal of Technology 1998 dari Presiden Bill Clinton atas jasa mereka dalam menemukan sistem operasi UNIX dan bahasa pemrograman C yang telah menyebabkan pengaruh akbar untuk perangkat keras komputer, perangkat lunak, dan sistem jaringan serta merangsang pertumbuhan industri sehingga membawa Amerika memimpin di Era Informasi.</li>
            <li>Japan Prize Pada tahun 2011, Dennis Ritchie bersama Ken Thompson menerima penghargaan Japan Prize for Information and Communications atas jasa mereka sebagai pionir dalam pengembangan sistem operasi UNIX.</li>
        </ul>
        <hr>
        <h4 id="14" class="text-center fw-bold">Anders Heljsberg</h4>
        <img src="{{ asset("img/anders.jpg") }}" class="img-fluid m-5 rounded mx-auto d-block img-responsive" style="width: 40%" alt="...">
        <p>Anders Hejlsberg (lahir Desember 1960) adalah seorang insinyur perangkat lunak Denmark terkemuka yang ikut merancang beberapa bahasa pemrograman dan alat pengembangan yang populer dan sukses secara komersial . Dia adalah penulis asli Turbo Pascal dan kepala arsitek Delphi . Dia saat ini bekerja untuk Microsoft sebagai arsitek utama C# dan pengembang inti di TypeScript .Hejlsberg lahir di Kopenhagen , Denmark , dan belajar teknik di Universitas Teknik Denmark tetapi tidak lulus. Sementara di universitas pada tahun 1980, ia mulai menulis program untuk komputer mikro Nascom , termasuk kompiler Pascal yang awalnya dipasarkan sebagai Perangkat Lunak Label Biru Pascal untuk Nascom-2.</p>
        <p>Namun, dia segera menulis ulang untuk CP/M dan DOS , memasarkannya pertama sebagai Compas Pascal dan kemudian sebagai PolyPascal . Kemudian produk tersebut dilisensikan ke Borland , dan diintegrasikan ke dalam IDE untuk menjadisistem Turbo Pascal . Turbo Pascal bersaing dengan PolyPascal. Kompiler itu sendiri sebagian besar terinspirasi oleh kompiler "Tiny Pascal" dalam " Algorithms + Data Structures = Program " Niklaus Wirth , salah satu buku ilmu komputer paling berpengaruh saat itu. Anders dan mitranya mengelola toko komputer di Kopenhagen dan memasarkan sistem akuntansi.</p>
        <p>Perusahaan mereka, PolyData, adalah distributor produk Microsoft di Denmark yang membuat mereka berselisih dengan Borland . Philippe Kahn dan Anders pertama kali bertemu pada tahun 1986. Selama bertahun-tahun, Niels Jensen, salah satu pendiri Borland dan pemegang saham mayoritasnya, berhasil menangani hubungan antara Borland dan PolyDataDi tangan Borland, Turbo Pascal menjadi salah satu kompiler Pascal yang paling sukses secara komersial. Hejlsberg tetap dengan PolyData sampai perusahaan berada di bawah tekanan keuangan, pada saat itu, pada tahun 1989 ia pindah ke California dan menjadi Chief Engineer di Borland. Di sana dia tinggal sampai tahun 1996. Selama waktu ini dia mengembangkan Turbo Pascal lebih lanjut, dan akhirnya menjadi kepala arsitek untuk tim yang menghasilkan pengganti Turbo Pascal, Delphi .</p>
        <p>Pada tahun 1996, Hejlsberg meninggalkan Borland dan bergabung dengan Microsoft. Salah satu pencapaian pertamanya adalah bahasa pemrograman J++ dan Windows Foundation Classes; dia juga menjadi Microsoft Distinguished Engineer dan Technical Fellow. Sejak tahun 2000, dia menjadi arsitek utama tim yang mengembangkan bahasa C# . Pada 2012 Hejlsberg mengumumkan proyek barunya TypeScript - superset dari JavaScript.Dia menerima 2001 Dr. Dobb's Excellence in Programming Award untuk karyanya pada Turbo Pascal, Delphi, C# dan Microsoft .NET Framework . Bersama dengan Shon Katzenberger, Scott Wiltamuth, Todd Proebsting, Erik Meijer, Peter Hallam dan Peter Sollich, Anders dianugerahi Technical Recognition Award for Outstanding Technical Achievement untuk karya mereka dalam bahasa C# pada tahun 2007. Video tentang ini tersedia di Microsoft Channel 9.</p>
        <p>Karya yang diterbitkan Bahasa Pemrograman C#, Edisi ke-2 , Addison-Wesley Professional, ISBN 0-321-33443-4, 9 Juni 2006 Bahasa Pemrograman C#, Edisi ke-3 , Addison-Wesley Professional, ISBN 0-321-56299-2, 18 Oktober 2008 Bahasa Pemrograman C#, Edisi ke-4 , Addison-Wesley Professional, ISBN 0-321-74176-5, ISBN 978-0-321-74176-9, Oktober 2010</p>
        <hr>
        <h4 id="15" class="text-center fw-bold">Samuel Finley Breese Morse</h4>
        <img src="{{ asset("img/morse.png") }}" class="img-fluid m-5 rounded mx-auto d-block img-responsive" style="width: 40%" alt="...">
        <p>Samuel Morse dilahirkan pada 27 April 1791 di Charlestown, Massachusetts. Anak dari pasangan Pastor Jedidiah Morse yang merupakan pakar geografi serta Elizabeth Ann Finley Breese.Setelah menempuh pendidikan di Akademi Phillips di Andover, Morse melanjutkan sekolah di Yale College untuk mempelajari Filsuf Religius, Matematika, dan Sains Kuda. Saat itu, dia juga mengikuti kuliah kelistrikan yang diberikan pakar kimia AS Benjamin Silliman dan Jeremiah Day. Pada 1810, dia lulus dengan menerima gelar dari warga akademik Phi Beta Kappa.Setelah lulus, sebenarnya Morse ingin mengejar karir sebagai pelukis. Namun ayahnya ingin dia memmpunyai pekerjaan mapan. Jadi, Jedidiah mendesak anaknya supaya belajar bersama penerbit di Boston.</p>
        <p>Namun, keteguhan Morse membuat ayahnya menyerah dan mengizinkannya untuk belajar seni di Inggris. Di sana, dia belajar bersama sejumlah seniman, termasuk Benjamin West di Royal Academy. Mengadopsi gaya lukisan "romantis", Morse menggunakan kanvas besar untuk melukis sebuah peristiwa sejarah epik maupun menggambarkan biografi heroik dalam pewarnaan yang brilian. Lima tahun kemudian, dia kembali ke AS dan mendirikan studio di Boston. Pada 1818, dia menikah dengan Lucretia Walker dan mempunyai tiga buah hati. Setelah membuka studio Morse menyadari,gaya lukisannya memang menarik perhatian, namun tidak secara penjualan sehingga dia mulai mengalami kesulitan keuangan.</p>
        <p>Morse pun menjadi seniman keliling yang bepergian dari New England ke Carolinas untuk mendapat pekerjaan. Saat itu, dia berhasil menyelesaikan dua mahakarya. Yakni lukisan dua tokoh Perang Kemerdekaan. Yakni Marquis de Lafayette dan George Washington yang merupakan presiden pertama Negeri "Uncle Sam".Antara 1825 hingga 1829, Morse dilanda kedukaan yang luar biasa. Diawali dari kematian istrinya Lucretia setelah melahirkan anak ketiga mereka pada Februari 1825. Setahun kemudian, ayahnya meninggal disusul ibunya tiga tahun kemudian. Dalam suasana duka, Morse memutuskan berkelana ke Eropa untuk memulihkan diri. Dalam perjalanan pulang di 1832, dia berkenalan dengan penemu Charles Thomas Jackson dan keduanya mendiskusikan bagaimana impuls listrik bisa diteruskan dengan kabel hingga jarak jauh.</p>
        <p>Morse yang tertarik kemudian membuat sketsa sebuah perangkat mekanik yang bisa menjalankan tugasnya. Dia kemudian membaca karya fisikawan Joseph Henry. Berdasarkan teori Henry itu, Morse kemudian mengembangkan purwarupa telegraf. Pada 1836, para ilmuwan Eropa juga tengah mengembangkan telegraf. Namun, saat itu tidak ada yang bisa mendapatkan mesin telegraf yang mampu beroperasi hingga jarak jauh, Pada 1838, dia bertemu dengan sesama penemu Alfred Vail. Vail menjadi penyandang dana sekaligus rekan penemu yang mengembangkan sistem titik dan garis untuk mengirimkan sinyal yang kelak dinamakan Sandi Morse. Selama bertahun-tahun, kemudian kesulitan mendapatkan investor hingga 1842, di mana Morse mendapatkan perhatian dari anggota Kongres Francis Ormand Jonathan Smith. Desember di tahun yang sama, Morse memasang kabel di antara dua ruangan komite Gedung Capitol dan berhasil mengirim pesan dari satu ruangan dan sebaliknya.</p>
        <p>Uji coba itu membuat Smith memberi dukungan sehingga Kongres memberi dana 30.000 dollar AS supaya Morse bisa melakukan demonstrasi dalam skala lebih besar.Maka dia menggelar uji coba memasang telegraf dari Washington hingga Baltimore, Maryland, sepanjang 61 km. Dia mengirim pesan yang hingga kini dikenang: "Lihatlah yang Tuhan Tempa". Ketika hampir memperoleh hak paten,Morse harus berurusan dengan pengadilan setelah dia mendapat serangan litigasi baik dari mitra maupun rival pada 1847. Pertikaian hukum itu berakhir setelah Mahkamah Agung AS menerbitkan putusan O'Reilly v Morse (1854) di mana Morse diputusan sebagai penemu telegraf pertama.Pada 1848, dia menikah kembali dengan Sarah Griswold di mana mereka dikaruniai empat anak. Setelah memenangkan perang hak paten, Morse mulai hidup makmur. Di masa akhirnya, dia memberikan donasi kepada Vassar College dan Yale College. Begitu juga dengan organisasi keagamaan maupun masyarakat sederhana. Samuel Morse meninggal akibat pneumonia pada 2 April 1872 dalam usia 80 tahun. Dia dimakamkan di Pemakaman Green-Wood di Brooklyn, New York.</p>
        <hr>
        <h4 id="16" class="text-center fw-bold">Sergey Mikhailovich Brin</h4>
        <img src="{{ asset("img/sergey.jpeg") }}" class="img-fluid m-5 rounded mx-auto d-block img-responsive" style="width: 40%" alt="...">
        <p>Sergey Brin lahir di Moskow, Rusia pada tanggal 21 Agustus 1973. Ia lahir dari orang tua keturunan Yahudi bernama Michael Brin dan Eugenia Brin. Ayahnya merupakan profesor matematika dan ibunya merupakan peneliti di NASA. Saat berusia enam tahun, Keluarganya bermigrasi ke Amerika saat orang Yahudi sangat sulit hidup di Moskow.Orang tuanya menyekolahkan Brin di Paint Branch Montessori School di Maryland. Ayahnya juga mendidik Brinbelajar matematika di rumah.Setelah menyelesaikan sekolah menengahnya, Sergey Brin kemudian melanjutkan studinya di Universitas Maryland. Ia fokus dalam bidang matematika dan ilmu komputer. Tahun 1993, Ia menyelesaikan kuliahnya dan menenrima gelar Bachelor of Science. Setelah itu, ia melanjutkan studi setelah menerima beasiswa beasiswa pascasarjana dari National Science Foundation.</p>
        <p>Ia mengambil bidang ilmu komputer di Universitas Stanford.Sergey Brin dan Larry Page bertemu dan berkenalan dalam sebuah proyek penelitian untuk tesis mereka. Sergey Brin yang kala itu merupakan mahasiswa pascasarjana menemani Larry Page yang saat itu merupakan mahasiswa doktoral Universitas Stanford.Sambil jalan, mereka berdiskusi mengenai konsep dari mesin pencarian. Larry Page tertarik mengeksplorasi sifat matematika dari World Wide Web dalam disertasinya. Konsep ini juga yang juga dianggap menarik oleh Brin.Sergey Brin dan Larry Page menemukan bahwa mereka memiliki ketertarikan yang sama bagaimana mencari dan menemukan informasi yang relevan dari sekumpulan data yang besar.</p>
        <p>Keduanya kemudian menulis makalah berjudul ‘The Anatomy of a Large-Scale Hypertextual Web Search Engine‘.Makalah ini menjadi salah satu makalah yang paling banyak diakses dan dibaca di Stanford University. Ini juga dianggap sebagai bibit awal bagi karir mereka dalam dunia teknologi. Mereka kemudian mulai bekerja sama dalam proyek penelitian yang disebut ‘BackRub.’ Awalnya, mesin perayap web digunakan untuk menjelajahi web situs Stanford.Mereka berdua kemudian menciptakan algoritma PageRank yang merangking halaman website. Hal ini berdasarkan menganalisis dari BackRub saat menggunakan algoritma tersebut. Mereka kemudian menyadari bahwa mesin pencari berdasarkan algoritma PageRank akan menghasilkan hasil pencarian yang lebih baik daripada teknik yang ada saat itu.</p>
        <p>Mereka terus menyempurnakan proyek penelitian mereka di komputer universitas. Proyek mereka berdua dijalankan di komputer Stanford selama berbulan-bulan. Awalnya, proyek ini menggunakan situs universitas dengan nama domain google.stanford.edu.Nama Google merupakan plesetan dari kata ‘Gogool’ yang merupakan bilangan terbesar. Tahun 1997, Sergey Brin dan Larry Page resmi mendaftarkan domain google.com. Perusahaan Google kemudian resmi berdiri pada tanggal 4 September 1998 di garasi seorang teman di Menlo Park, California.Saat itu, Andy Bechtolsheim pendiri Sun Microsystems menanamkan modalnya sebesar 100 ribu dollar melalui cek ke Google. Pada tahun 1999, perusahaan Google mulai beroperasi dengan delapan karyawan. Larry Page dan Sergey Brin bertindak sebagai founder dan co founder.</p>
        <p>Mereka kemudian memindahkan kantor Google ke Palo Alto di California. Kompleks kantor tersebut kemudian dikenal dengan nama ‘Googleplex.’Selama beberapa tahun berikutnya, dibawah kendali Sergey Brin dan Larry Page, Google sukses meluncurkan banyak fitur baru. Mereka juga terus menyempurnakan mesin pencari Google agar bisa bersaing dengan Yahoo kala itu.Dengan perkembangan yang pesat sebagai sebuah perusahaan teknologi, Google berhasil mengakuisisi beberapa perusahaan internet lain. Mereka juga menjalin kemitraan dengan perusahaan lain untuk menjadi salah satu perusahaan internet dengan pertumbuhan paling cepat di dunia. Google menjadi sebuah pencapaian terbesar dalam hidup Sergey Brin bersama Larry Page. Perusahaan yang ia dirikan dari sebuah garasi pada tahun 1998 telah tumbuh pesat dan mencapai kesuksesan yang luar biasa dalam waktu yang singkat. Sergey Brin dan Larry Page telah merevolusi bagaimana cara dunia mencari informasi di Internet.</p>
        <p>Perusahaan Google ciptaan Sergey Brin dan Larry Page terus berkembang pesat menjadi perusahaan teknologi terbaik di dunia. Mesin pencarian Google menjadi mesin pencari nomor satu di dunia yang paling banyak digunakan. Selain itu, perusahaan Sergey Brin dan Larry Page ini terus berinovasi mengembangkan teknologi bukan hanya pada mesin pencari saja tetapi pada semua produk internet. Misalnya dengan mengakuisisi Youtube. Pendapatan google lebih banyak disumbangkan dari iklan.Bersama dengan rekannya Larry Page, Sergey Brin dinobatkan sebagai salah satu dari 100 inovator teratas di dunia di bawah usia 35 tahun oleh MIT Technology Review TR100. Pendiri Google ini juga menerima gelar kehormatan MBA dari IE Business School.Ia jugga menerima penghargaan dari Yayasan Marconi yakni “Penghargaan Tertinggi di bidang Teknik” bersama Larry Page pada tahun 2004.</p>
        <hr>
        <h4 id="17" class="text-center fw-bold">Stephen Gary Wozniak</h4>
        <img src="{{ asset("img/steve.jpg") }}" class="img-fluid m-5 rounded mx-auto d-block img-responsive" style="width: 40%" alt="...">
        <p>Stephan Gary Wozniak lahir pada 11 Agustus 1950, di San Jose, California, A.S. Dia adalah putra Francis Jacob “Jerry” Wozniak dan Margaret Louise Wozniak.Steve Wozniak lulus dari Homestead High School pada tahun 1968. Kemudian dia masuk ke University of Colorado Boulder, namun dia dikeluarkan karena melakukan hack di sistem komputer universitas. Setelah itu dia mendaftar kembali di De Anza College lalu dipindahkan ke University of California, Berkeley pada tahun 1971. Namun dia memutuskan untuk dropout dan mulai bekerja di Hewlett-Packard, di mana dia bekerja pada komputer mainframe dan merancang kalkulator. Pada saat inilah dia berteman dengan Steve Jobs. Awalnya Wozniak diperkenalkan ke Jobs oleh Fernandez, saat menghadiri Homestead High School bersama Jobs pada tahun 1971. Jobs dan Wozniak menjadi teman ketika mereka berdua bekerja di perusahaan yang sama yakni di HP.Pada tahun 1975, Wozniak mulai merancang dan mengembangkan komputer yang disebut dengan, Apple I. Pada tahun 1976, Wozniak menyelesaikan desain Apple I.</p>
        <p>Dia sendiri yang merancang perangkat keras, desain, dan sistem operasi untuk komputer tersebut. Wozniak awalnya menawarkan desain komputer itu kepada HP saat masih bekerja di sana, tetapi ditolak oleh perusahaan.Steve Jobs memiliki ide untuk menjual Apple I sebagai printed circuit board. Wozniak, pada awalnya menolak ide tersebut, namun diyakinkan oleh Steve Jobs bahwa ide itu mungkin akan berhasil dan sukses besar. Bersama-sama mereka menjual sebagian harta mereka untuk modal dan mengumpulkan $ 1.300. mereka merancang dan mengembangkan komputer pribadi pertama untuk tujuan komersial. Apple I dijual dengan harga $ 666,66.Pada 1 April 1976, Steve Jobs dan Wozniak mendirikan perusahaan bernama Apple Computer (sekarang disebut Apple Inc.) bersama dengan pengawas administrasi Ronald Wayne.</p>
        <p>Wozniak mengundurkan diri dari pekerjaannya di Hewlett-Packard dan menjadi wakil presiden Apple yang bertanggung jawab atas penelitian dan pengembangan di Apple. Setelah kesuksesan Apple I, Wozniak kemudian merancang dan mengembangkan Apple II, komputer pribadi pertama yang memiliki kemampuan untuk menampilkan grafik warna, dan bahasa pemrograman BASIC built-in.Steve Jobs dan Wozniak memperkenalkan Apple II di West Coast Computer Faire 1977. Itu menjadi salah satu komputer pribadi produksi massal pertama yang sangat sukses di dunia.Pada tahun 1980, Apple menjadi perusahaan publik dengan keuntungan finansial yang signifikan, hal ini menjadikan Steve Jobs dan Wozniak sebagai miliarder di dunia.Pada pertengahan 1980-an, dia merancang Apple Desktop Bus, sebuah periferal serial-bit yang diperkenalkan pada banyak model komputer Macintosh dan NeXT.</p>
        <p>Meskipun produk-produk yang ia hasilkan menyumbangkan sekitar 85% dari penjualan Apple, namun pertemuan tahunan Apple pada Januari 1985 tidak menyebut-nyebut divisi atau karyawan Apple II, hal inilah yang membuat Wozniak kecewa dan frustrasi. Wozniak bersekolah di Homestead High School dan lulus pada tahun 1968. Dia kemudian bergabung dengan University of Colorado Boulder tetapi dikeluarkan pada tahun pertamanya setelah ketahuan mengirim pesan di sistem komputer Universitas dan dia kembali ke Bay Area pada tahun 1969. Ini adalah waktunya sebagai proyek otodidak, Wozniak merancang dan membuat komputer Cream Soda dengan temannya Bill Fernandez. Dia kemudian memutuskan untuk mendaftar di De Anza College dan kemudian dia dipindahkan ke Universitas California, Berkely pada tahun 1971. Sebelum bergabung dengan Apple Steve Wozniak bekerja di Hewlett-Packard (HP) di mana dia merancang kalkulator Wozniak merasa keberadaannya tidak lagi dibutuhkan di Apple. Kemudian pada awal 1985, Wozniak meninggalkan Apple dan menjual sebagian besar sahamnya di Apple. Untuk kontribusinya terhadap teknologi, Wozniak telah dianugerahi sejumlah gelar Doktor Kehormatan Teknik, yang meliputi:</p>
        <ul>
            <li>University of Colorado Boulder: 1989</li>
            <li>North Carolina State University: 2004</li>
            <li>Kettering University: 2005</li>
            <li>Southeastern University, Fort Lauderdale: 2005</li>
            <li>ESPOL University in Ecuador: 2008</li>
            <li>Michigan State University, in East Lansing 2011</li>
            <li>Concordia University in Montreal, Canada: June 22, 2011</li>
            <li>State Engineering University of Armenia: November 11, 2011</li>
            <li>Santa Clara University: June 16, 2012</li>
            <li>University Camilo José Cela in Madrid, Spain: November 8, 2013</li>
        </ul>
        <hr>
    </div>
    <button type="button" class="btn btn-dark m-5"><a style="text-decoration: none;color:white" href="/header">Back to Home</a></button>
    @include('pages/footer')
</body>
</html>